[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.11"
tokio = {version = "^1", features = ["full"]}
sea-orm = {version = "^0.12.0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"]}
time = "0.3"
common = { path = "../common" }