[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5"
rand = "0.8"
diplomacy = {version = "0.2.0", features = ["serde"]} 
serde = { version = "1.0", features = ["derive"] }
